[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = {path = "../lib"}
tokio = { version = "1.41.1", features = ["full"] }
clap = { version = "4.5.21", features = ["derive"] }
anyhow = "1.0.93"
flume = "0.11.1"
